version: "3.7"

volumes:
  shared-workspace:
    name: "docker-spark-volume"
    driver: local
  esdata:
    name: "docker-elastic-volume"
    driver: local

services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    deploy:
      resources: 
        limits: 
          cpus: "1"
          memory: 1G
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace

  spark-master:
    image: spark-master
    container_name: spark-master
    deploy:
      resources: 
        limits: 
          cpus: "1"
          memory: 1G
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    deploy:
      resources: 
        limits: 
          cpus: "1"
          memory: 1G
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    deploy:
      resources: 
        limits: 
          cpus: "1"  
          memory: 1G       
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-3:
    image: spark-worker
    container_name: spark-worker-3
    deploy:
      resources: 
        limits: 
          cpus: "1"  
          memory: 1G       
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    ports:
      - 8083:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    deploy:
      resources: 
        limits: 
          cpus: "1" 
          memory: 1G       
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  hq:
    image: elastichq/elasticsearch-hq
    container_name: elastic-hq
    deploy:
      resources: 
        limits: 
          cpus: "1"  
          memory: 1G       
    ports:
      - "5000:5000"
    environment:
      HQ_DEFAULT_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
  